services:
  - type: web
    name: tiktok-mafia-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        sync: false # يسمح بتعديل القيمة من لوحة التحكم
